version: '3'

services: 
    site:
        build: ./muaz=rehman-site
        environment: 
            - REACT_APP_PORT=${REACT_APP_PORT}
        expose:
            - ${REACT_APP_PORT}
        ports: 
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        volumes: 
            - ./muaz-rehman-site/src:/srv/app/muaz-rehman-site/src
            - ./muaz-rehman-site/public:/srv/app/muaz-rehman-site/public
        links:
            - server
        command: npm run start