version: '3'

services: 
    site:
        build: ./muaz-rehman-site
        environment: 
            - REACT_APP_PORT=${REACT_APP_PORT}
        expose:
            - ${REACT_APP_PORT}
        ports: 
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        volumes: 
            - ./muaz-rehman-site/src:/var/www/html
            - ./muaz-rehman-site/public:/var/www/html/public
        command: npm run start